version: "3.9"
    
services:
  details:
    build: src/details/
    image: reviewer_details:${TAG}
    restart: always
  mongodb:
    build: src/mongodb/
    image: reviewer_mongodb:${TAG}
    restart: always
  mysql:
    build: src/mysql/
    image: reviewer_mysql:${TAG}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress    
  productpage:
    build: src/productpage/
    image: reviewer_productpage:${TAG}
    depends_on:
      - mongodb
      - details
      - reviews
    environment:
      FLOOD_FACTOR: 0
    ports:
      - "9080:9080"
    restart: always
  ratings:
    build: src/ratings
    image: reviewer_ratings:${TAG}
    restart: always
  reviews:
    image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
    depends_on:
      - ratings
    environment:
      SERVICE_VERSION: v2
      ENABLE_RATINGS: 'true'
      STAR_COLOR: gold 
    restart: always

