apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: details
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
        - name: my-details-dock
          image: reviewer_details:v1.2
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
