apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-deployment
  labels:
    app: details
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: details-deployment
  template:
    metadata:
      labels:
        app: details-deployment
    spec:
      containers:
        - name: my-details-dock
          image: reviewer_details:v1.2
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
