apiVersion: v1
kind: Pod
metadata:
  name: details-pod
  labels:
    app: details
spec:
  containers:
    - name: my-pod-dock
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
