apiVersion: v1
kind: Deployment
metadata:
  name: details-deployment
  labels:
    app: details
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: details-deployment
  template:
    metadata:
      labels:
        app: details-deployment
    spec:
      containers:
        - name: my-details-dock
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
