apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
        - name: my-productpage-dock
          image: reviewer_productpage:v1.2
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
