apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
    color: blue
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: ratings
      color: blue
  template:
    metadata:
      labels:
        app: ratings
        color: blue
    spec:
      containers:
        - name: my-ratings-dock
          image: reviewer_ratings:v1.2
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
