apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingsv2
  labels:
    app: ratings
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
        - name: my-ratingsv2-dock
          image: docker.io/istio/examples-bookinfo-ratings-v2
          env:
            - name: DB_TYPE
              value: "mysql"
            - name: MYSQL_DB_HOST
              value: mysql
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USER
              value: root
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecrets
                  key: password
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
