apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: my-reviews-dock
          image: reviewer_reviews:v1.2
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - name: web
              containerPort: 9080
              protocol: TCP
          env:
            - name: SERVICE_VERSION
              value: v2
            - name: ENABLE_RATINGS
              value: 'true'
            - name: STAR_COLOR
              value: 'gold'
