apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  type: NodePort
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
    nodePort: 30123
  selector:
    app: productpage
